loader: make loader completely generic
brutal-org/brutal pull request #111
Opened 2022-02-19 15:44 UTC by Abb1x

2022-02-21 18:16 UTC, sleepy-monax requested changes

2022-02-21 18:16 UTC, sleepy-monax commented on sources/embed/boot.h
> +#pragma once
This shouldn't be in embed/

2022-02-21 18:16 UTC, sleepy-monax commented on sources/embed/mem.h
> +#include <bal/boot/handover.h>
Don't include bal stuff in embed/

2022-02-21 18:16 UTC, sleepy-monax commented on sources/libs/bal/hw/mem.h
>  void bal_mem_unpack(IpcUnpack *pack, BalMem *self);
Please follow our editor config.

2022-02-21 18:16 UTC, sleepy-monax commented on sources/libs/brutal/parse/lex.h
> +        })
Why

2022-02-21 18:16 UTC, sleepy-monax commented on sources/libs/brutal/parse/scan.h
> +        })
Why

2022-02-21 18:16 UTC, sleepy-monax commented on sources/libs/brutal/ui/view.h
> +    })
Why

2022-02-21 18:16 UTC, sleepy-monax commented on sources/libs/stdc/math/libm.h
> +      }){.__xy = {(x), (y)}} \
This is way out of scope of this PR

2022-02-21 18:16 UTC, sleepy-monax commented on sources/loader/loader.h
> +#include <bal/boot.h>
missing new line after `#pragma`

2022-02-21 18:16 UTC, sleepy-monax commented on sources/loader/main.c
> +#include <loader/protocol.h>
Only library includes should be wrapped in <>

2022-02-21 18:16 UTC, sleepy-monax commented on sources/loader/efi/entry.c
> +}
useless function

2022-02-23 13:49 UTC, Supercip971 requested changes

2022-02-23 13:49 UTC, Supercip971 commented on sources/loader/loader.h
> +enum loader_mem_flag
Use a typedef:
```c
typedef enum
{

} LoaderMemFlag;
```

2022-02-23 13:49 UTC, Supercip971 commented on sources/loader/loader.h
> +// Entry of the loader, called by the platform's entry point. This is needed because of EFI requiring parameters to be passed to its entry point
Maybe add doxygen doc instead of a comment

2022-02-23 13:49 UTC, Supercip971 commented on sources/loader/main.c
>      memory_switch(vmm);
The memory switch should be the last thing we do before jumping into the kernel.

2024-09-08 20:59 UTC, closed without merging