tasking + random improvment
brutal-org/brutal pull request #16
Opened 2021-06-11 17:53 UTC by Supercip971

2021-06-11 17:54 UTC, Supercip971 commented
merci de pas merge uwu

2021-06-11 22:50 UTC, Supercip971 commented
maintenant c'est fix :sueur:

2021-06-12 09:42 UTC, sleepy-monax requested changes
Voilà la première partie de la review, j'ai du boulot a faire donc je continuerai plus tard ;)

2021-06-12 11:38 UTC, Supercip971 commented on sources/host/linux/task.c
> +    if (handle == (task_id_t)TASK_THIS)
TASK_THIS c'est une implémentation coté linux

2021-06-12 12:38 UTC, sleepy-monax commented on sources/host/linux/task.c
> +    if (handle == (task_id_t)TASK_THIS)
Non ils sont implémenté tout les deux du côté de libbrutal

2021-06-12 12:46 UTC, Supercip971 commented on sources/host/linux/task.c
> +    if (handle == (task_id_t)TASK_THIS)
mais je vois pas l'intéret de rendre task_id_t unsigned

2021-06-12 13:07 UTC, sleepy-monax commented on sources/host/linux/task.c
> +    if (handle == (task_id_t)TASK_THIS)
Pour éviter le warning car TASK_THIS = -1

2021-06-12 13:33 UTC, Supercip971 commented on sources/host/linux/task.c
> +    if (handle == (task_id_t)TASK_THIS)
j'ai changé task_this à 0 (son ancienne valeur était de -424242)

2021-06-13 15:39 UTC, sleepy-monax approved these changes

2021-06-13 15:39 UTC, merged