<stdio.h>
brutal-org/brutal pull request #32
Opened 2021-07-15 14:16 UTC by NeKroFR

**work in progresss**

2021-07-15 20:08 UTC, Supercip971 requested changes

2021-07-15 20:08 UTC, Supercip971 commented on sources/libc/ansi/stdio.h
> +fpos_t
pourquoi tu a mit juste fpos_t

2021-07-15 20:08 UTC, Supercip971 commented on sources/libc/ansi/stdio.h
> +
juste un espace ;)

2021-07-15 20:08 UTC, Supercip971 commented on sources/libc/ansi/stdio.h
> +
il faudrait utiliser stddef stdint ...

2021-07-15 20:08 UTC, Supercip971 commented on sources/libc/ansi/stdio.h
> +const int SEEK_SET (4);
ici il faudrait utiliser un define ou alors 
const int SEEK_CUR = 2;

2021-07-15 20:08 UTC, Supercip971 commented on sources/libc/ansi/stdio.h
> +#define FILE size_t
file ne devrait pas être égal à un size_t

2021-07-15 20:08 UTC, Supercip971 commented on sources/libc/ansi/stdio.h
> +#define EOF setbuf
EOF ne devrait pas être égal à une fonction

2021-07-17 19:07 UTC, NeKroFR commented on sources/libc/ansi/stdio.h
> +fpos_t
parce que je ne sais pas comment l'implémenter donc je le laisse la pour le moment

2021-07-17 19:09 UTC, NeKroFR commented on sources/libc/ansi/stdio.h
> +
où?

2021-07-17 19:13 UTC, NeKroFR commented on sources/libc/ansi/stdio.h
> +const int SEEK_SET (4);
fait

2021-07-18 08:24 UTC, NeKroFR commented on sources/libc/ansi/stdio.h
> +
fait

2021-07-25 13:53 UTC, closed without merging